"""initial schema

Revision ID: 1aed9ad3e04b
Revises: 
Create Date: 2026-09-06 05:24:25.733866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aed9ad3e04b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('expertise_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERT', name='expertiselevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('task_type', sa.Enum('CLASSIFICATION', 'REGRESSION', 'UNSET', name='tasktype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['dataset_versions.id'], use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('blockchain_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_record_id'], ['blockchain_records.id'], use_alter=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_sha256_hash'), 'dataset_versions', ['sha256_hash'], unique=False)
    op.create_table('knowledge_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('memory_type', sa.Enum('RECOMMENDATION', 'PREFERENCE', 'PAST_DECISION', name='memorytype'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockchain_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('DATASET_REGISTERED', 'DATASET_VERIFIED', 'DATASET_REVOKED', name='chainaction'), nullable=False),
    sa.Column('chain_status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='chainstatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('profiling_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='experimentstatus'), nullable=False),
    sa.Column('best_model_result_id', sa.String(length=36), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['best_model_result_id'], ['model_results.id'], use_alter=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'AGENT', name='conversationrole'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('related_experiment_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversations_session_id'), 'agent_conversations', ['session_id'], unique=False)
    op.create_table('experiment_iterations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.Enum('PROFILING', 'PREPROCESSING', 'MODEL_SELECTION', 'TRAINING', 'HPO', 'EVALUATION', name='stepname'), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'RUNNING', 'COMPLETED', 'WARNING', 'FAILED', name='stepstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('log_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('hyperparameters_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('training_time_ms', sa.Integer(), nullable=False),
    sa.Column('feature_importance_json', sa.JSON(), nullable=True),
    sa.Column('confusion_matrix_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optuna_trials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_result_id', sa.String(length=36), nullable=False),
    sa.Column('trial_number', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETE', 'PRUNED', 'FAILED', name='trialstatus'), nullable=False),
    sa.ForeignKeyConstraint(['model_result_id'], ['model_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optuna_trials')
    op.drop_table('model_results')
    op.drop_table('experiment_iterations')
    op.drop_index(op.f('ix_agent_conversations_session_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_table('experiments')
    op.drop_table('dataset_metadata')
    op.drop_table('blockchain_records')
    op.drop_table('knowledge_memory')
    op.drop_index(op.f('ix_dataset_versions_sha256_hash'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
