/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DatasetRegistry {
  export type RegistrationStruct = {
    hash: BytesLike;
    version: BigNumberish;
    timestamp: BigNumberish;
    registeredBy: AddressLike;
  };

  export type RegistrationStructOutput = [
    hash: string,
    version: bigint,
    timestamp: bigint,
    registeredBy: string
  ] & {
    hash: string;
    version: bigint;
    timestamp: bigint;
    registeredBy: string;
  };
}

export interface DatasetRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getDatasetHistory" | "registerDataset" | "verifyDataset"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DatasetRegistered" | "DatasetVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getDatasetHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDataset",
    values: [string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDataset",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getDatasetHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDataset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDataset",
    data: BytesLike
  ): Result;
}

export namespace DatasetRegisteredEvent {
  export type InputTuple = [
    datasetId: string,
    hash: BytesLike,
    version: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: string,
    hash: string,
    version: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    datasetId: string;
    hash: string;
    version: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DatasetVerifiedEvent {
  export type InputTuple = [
    datasetId: string,
    matches: boolean,
    checkedVersion: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: string,
    matches: boolean,
    checkedVersion: bigint
  ];
  export interface OutputObject {
    datasetId: string;
    matches: boolean;
    checkedVersion: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DatasetRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DatasetRegistry;
  waitForDeployment(): Promise<this>;

  interface: DatasetRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDatasetHistory: TypedContractMethod<
    [datasetId: string],
    [DatasetRegistry.RegistrationStructOutput[]],
    "view"
  >;

  registerDataset: TypedContractMethod<
    [datasetId: string, hash: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyDataset: TypedContractMethod<
    [datasetId: string, currentHash: BytesLike],
    [[boolean, bigint] & { matches: boolean; registeredVersion: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDatasetHistory"
  ): TypedContractMethod<
    [datasetId: string],
    [DatasetRegistry.RegistrationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerDataset"
  ): TypedContractMethod<
    [datasetId: string, hash: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDataset"
  ): TypedContractMethod<
    [datasetId: string, currentHash: BytesLike],
    [[boolean, bigint] & { matches: boolean; registeredVersion: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "DatasetRegistered"
  ): TypedContractEvent<
    DatasetRegisteredEvent.InputTuple,
    DatasetRegisteredEvent.OutputTuple,
    DatasetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DatasetVerified"
  ): TypedContractEvent<
    DatasetVerifiedEvent.InputTuple,
    DatasetVerifiedEvent.OutputTuple,
    DatasetVerifiedEvent.OutputObject
  >;

  filters: {
    "DatasetRegistered(string,bytes32,uint256,uint256)": TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;
    DatasetRegistered: TypedContractEvent<
      DatasetRegisteredEvent.InputTuple,
      DatasetRegisteredEvent.OutputTuple,
      DatasetRegisteredEvent.OutputObject
    >;

    "DatasetVerified(string,bool,uint256)": TypedContractEvent<
      DatasetVerifiedEvent.InputTuple,
      DatasetVerifiedEvent.OutputTuple,
      DatasetVerifiedEvent.OutputObject
    >;
    DatasetVerified: TypedContractEvent<
      DatasetVerifiedEvent.InputTuple,
      DatasetVerifiedEvent.OutputTuple,
      DatasetVerifiedEvent.OutputObject
    >;
  };
}
